name = "Quasar"
uuid = "1b0303c1-8819-4d1c-a929-91cb710ac874"
authors = ["Kareem Fareed"]
version = "1.0.0-DEV"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
ForwardDiff = "1.3.2"
julia = "1.11"
