name = "QuantNova"
uuid = "1b0303c1-8819-4d1c-a929-91cb710ac874"
authors = ["Kareem Fareed"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YFinance = "e4b3b0a2-f9a3-42f3-aabb-32142cceaf77"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[extensions]
QuantNovaEnzymeExt = "Enzyme"
QuantNovaReactantExt = ["Enzyme", "Reactant"]

[compat]
DiffResults = "1"
Distributions = "0.25.123"
Enzyme = "0.13"
ForwardDiff = "1.3.2"
Makie = "0.24.8"
Plots = "1.41.4"
Reactant = "0.2"
Sobol = "1.5.0"
YFinance = "0.1.11"
julia = "1.11"
