name = "Quasar"
uuid = "1b0303c1-8819-4d1c-a929-91cb710ac874"
authors = ["Kareem Fareed"]
version = "0.1.0"

[deps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extensions]
QuasarEnzymeExt = "Enzyme"
QuasarReactantExt = "Reactant"

[compat]
DiffResults = "1"
Distributions = "0.25.123"
Enzyme = "0.13"
ForwardDiff = "1.3.2"
Plots = "1.41.4"
Reactant = "0.2"
julia = "1.11"
