name = "QuantNova"
uuid = "1b0303c1-8819-4d1c-a929-91cb710ac874"
version = "0.1.1"
authors = ["Kareem Fareed"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YFinance = "e4b3b0a2-f9a3-42f3-aabb-32142cceaf77"

[weakdeps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[extensions]
QuantNovaBonitoExt = ["Bonito", "WGLMakie"]
QuantNovaEnzymeExt = "Enzyme"
QuantNovaMakieExt = ["Makie"]
QuantNovaReactantExt = ["Enzyme", "Reactant"]

[compat]
Bonito = "3, 4"
CairoMakie = "0.12, 0.13"
DiffResults = "1"
Distributions = "0.25.123"
Enzyme = "0.13"
ForwardDiff = "1.3.2"
GLMakie = "0.10, 0.11"
Makie = "0.21, 0.22"
Plots = "1.41.4"
PrecompileTools = "1.2.1"
Reactant = "0.2"
Sobol = "1.5.0"
Statistics = "1"
WGLMakie = "0.10, 0.11"
YFinance = "0.1.11"
julia = "1.10, 1.11"
